# Generated by Django 5.0.7 on 2024-08-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_item_changes_suggested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='changes_suggested',
            field=models.TextField(blank=True, default=None),
        ),
    ]
