# Generated by Django 5.0.7 on 2024-08-01 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_item_changes_suggested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='changes_suggested',
        ),
    ]
